name: face
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - ffmpeg
  - pip
  - pip:
    - opencv-contrib-python
    - cvzone==1.6.1
    - mediapipe==0.10.14
    - torch
    - torchvision
    - timm
    - transformers
    - openai-whisper
    - sounddevice
    - requests
    - ur-rtde
